services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    environment:
      - VITE_GOOGLE_URL=${VITE_GOOGLE_URL}
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./server/date.json:/app/server/date.json
    environment:
      - NODE_ENV=production
