FROM node:20-alpine as build

WORKDIR /app
COPY package*.json ./
COPY .env ./
COPY vite.config.js ./
COPY index.html ./
COPY src ./src

RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
